config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  devise_for :users
  resources :users
  resources :blogs
  resources :comments

  resources :blogs do
    resources :likes
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	
	validates_presence_of   :text, :image

	# validates             :image, :file_size => { less_than_or_equal_to: 10.megabyte }
  	mount_uploader :image, BlogUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog
	belongs_to :user

	validates_presence_of   :text

	# Return all comments row
	scope :all_comments, -> {
		joins(:user).select('comments.*, users.name as sender_name, users.email as sender_email')
	}

	#Return all comments of the blog
	scope :get_blog_comments, ->(blog_id, all_comments) {
		all_comments.select{ |a| a.comment_id.nil? && a.blog_id == blog_id }
	}

	# Return all replies of the particular Comment
	def get_replies(all_comments)
		all_comments.select{ |a| a.comment_id == self.id }
	end

end

app/models/like.rb
class Like < ApplicationRecord
	validates_presence_of   :user_id, :blog_id
	belongs_to :user
	belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
  def new
    @blog = Blog.new
  end
 
  def create
    @blog = current_user.blogs.new(blog_params)
    if @blog.save
       	flash[:success] = "Blog Created Successfully!"
    else
        flash[:error] = @blog.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end
 
  private
 
  def blog_params
    params.require(:blog).permit(:text, :image)
  end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def new
    @comment = Comment.new
  end
 
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
       	flash[:success] = "Commented successfully!"
    else
        flash[:error] = @comment.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end
 
  private
 
  def comment_params
    params.require(:comment).permit(:text, :blog_id, :text, :comment_id)
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @blogs = Blog.joins(:user).left_joins(:likes).select("blogs.*, users.email as email, COUNT(likes.id) AS likes_count").order("created_at DESC").group("blogs.id")
    @all_comments = Comment.all_comments
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 	
	before_action :find_blog

	def index
		@likes = Like.joins(:user, :blog).select("users.email as email").where("blogs.id = ?", @blog.id)
		render json: {status: true, liked_by: @likes.map(&:email)}, status: 200
	end

  	def create
  		if already_liked?
  			flash[:alert] = "Post Already Liked"
  		else
  			@blog.likes.create(:user_id => current_user.id)
  		end
  		redirect_to root_path
  	end
 
  	private
 
  	def find_blog
    	@blog = Blog.find(params[:blog_id])
  	end
 	
 	def already_liked?
 		Like.where(:user_id => current_user.id, :blog_id => @blog.id).exists?
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_blogs.html.erb
<div align="center">
    <%= form_for Blog.new do |f| %>
    <%= f.text_field :text %><br><br>
    <%= f.file_field :image %><br><br>
    <%= f.submit %>
    <% end %>
</div>


<% @blogs.each do |blog| %>
    <h3><%= blog.email %></h3>
    <h4><%= blog.text %></h4>
    <%= image_tag(blog.image.url, alt: 'Image', width: 'auto', height: 300) if blog.image? %>
    <br><br>

    <!-- Like Info -->
    <span id="myBtn" data-id=<%= blog.id %> ><%= blog.likes_count %> likes</span>
    <%= link_to blog_likes_path(blog.id), method: :post do %>
    <i class="fas fa-thumbs-up"></i>
    <% end %>

    <!-- Like Modal -->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="liked_user_list">
            	<h4>Liked By..</h4>
            </div>
        </div>
    </div>
    <br><br>

    <!-- comment form -->
    <%= form_for Comment.new do |f| %>
        <%= hidden_field_tag "comment[blog_id]", blog.id %>
        <%= f.text_area :text %>
        <%= f.submit "Comment" %>
    <% end %><br>

    <!-- Listing Comments of Blog -->
    <% Comment.get_blog_comments(blog.id, @all_comments).each do |comment| %>
        <div style="margin-left: 5%;">
            <div>
                <%= comment.sender_email %>:
                <%= comment.text %>
            </div>
            <div style="margin-left: 5%;">
                
                <!-- Comment Reply List -->
                <% comment.get_replies(@all_comments).each do |comment| %>
                <div>
                    <%= comment.sender_email %>:
                    <%= comment.text %>
                </div>
                <% end %>

                <!-- Reply Form -->
                <%= form_for Comment.new do |f| %>
                    <%= hidden_field_tag "comment[blog_id]", blog.id %>
                    <%= hidden_field_tag "comment[comment_id]", comment.id %>
                    <%= f.text_area :text %>
                    <%= f.submit "Reply" %>
                <% end %>
            </div>
        </div>
    <% end %>
    <br>
<% end %>

<script>
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the modal
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

app/views/homes/_notification.html.erb
<script>
function setCsrfToken(xhr) {
    xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
}

<% if flash[:notice].present? %>
message = "<%= flash[:notice]%>"
type = 'success'
notification(message, type)
<%end%>

<% if flash[:alert].present? %>
message = "<%= flash[:alert]%>"
type = 'warn'
notification(message, type)
<%end%>

<% if flash[:message].present?%>
message = "<%= flash[:message]%>"
type = 'info'
notification(message, type)
<%end%>

<% if flash[:errors].present?%>
<% if flash[:errors].class == Array %>
<%flash[:errors].each do |err|%>
message = "<%= err.html_safe %>"
type = 'error'
notification(message, type)
<%end%>
<% else %>
message = "<%= flash[:errors] %>"
type = 'error'
notification(message, type)
<% end %>
<% end %>

function notification(message, type) {
    $.notify(message, {
        className: type,
        clickToHide: true,
        globalPosition: 'top center',
        autoHideDelay: 5000,
        width: 500,
        height: 300
    });
}
</script>

app/views/homes/index.html.erb
<center>
    <h2>Hello
        <%= current_user.email %>
        <hr>
</center>
<div align="right">
    <%= button_to "Log out", destroy_user_session_path, method: :delete  %>
</div>
<div id="blogs">
	<%= render 'blogs' %>
</div>

app/views/layouts/_notification.html.erb
<script>
function setCsrfToken(xhr) {
    xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
}

<% if flash[:notice].present? %>
    message = "<%= flash[:notice]%>"
    type = 'success'
    notification(message, type)
<%end%>

<% if flash[:alert].present? %>
    message = "<%= flash[:alert]%>"
    type = 'warn'
    notification(message, type)
<%end%>

<% if flash[:message].present?%>
    message = "<%= flash[:message]%>"
    type = 'info'
    notification(message, type)
<%end%>

<% if flash[:errors].present?%>
    <% if flash[:errors].class == Array %>
        <%flash[:errors].each do |err|%>
            message = "<%= err.html_safe %>"
            type = 'error'
            notification(message, type)
        <%end%>
    <% else %>
        message = "<%= flash[:errors] %>"
        type = 'error'
        notification(message, type)
    <% end %>
<% end %>

function notification(message, type) {
    $.notify(message, {
        className: type,
        clickToHide: true,
        globalPosition: 'top center',
        autoHideDelay: 5000,
        width: 500,
        height: 300
    });
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js" integrity="sha512-efUTj3HdSPwWJ9gjfGR71X9cvsrthIA78/Fvd/IN+fttQVy7XWkOAXb295j8B3cmm/kFKVxjiNYzKw9IQJHIuQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <p class="notice"><%#= notice %></p> -->
    <!-- <p class="alert"><%#= alert %></p> -->
    <%= yield %>
    <%= render 'layouts/notification' %>
  </body>
</html>

<style>